# Supabase CLI — https://supabase.com/docs/guides/cli/config
project_id = "astrocus"

[api]
enabled = true
port = 54321

[db]
port = 54322
major_version = 15

[auth]
enabled = true
site_url = "http://localhost:8081"
